# Generated by Django 4.1.5 on 2023-01-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usercards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usercards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='usercards.usercards')),
            ],
        ),
    ]
