# Generated by Django 4.1.5 on 2023-01-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
        ('usercards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercards',
            name='template',
        ),
        migrations.AddField(
            model_name='usercards',
            name='template',
            field=models.ManyToManyField(related_name='usercards', to='templates.templates'),
        ),
    ]
