# Generated by Django 4.1.5 on 2023-01-23 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usercards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercards',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
