# Generated by Django 4.1.5 on 2023-01-24 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usercards', '0002_usercards_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercards',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercards', to=settings.AUTH_USER_MODEL),
        ),
    ]
