# Generated by Django 4.1.5 on 2023-01-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercards', '0003_alter_usercards_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercards',
            name='owner',
        ),
    ]
